server:
  port: 8080
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    name: VehicleAPI
pricing:
  endpoint: http://localhost:8082
maps:
  endpoint: http://localhost:8081